# Generated by Django 2.2.7 on 2019-12-10 16:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, default='FName', max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(db_index=True, default='LName', max_length=20, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Actor',
                'verbose_name_plural': 'Actors',
                'ordering': ['first_name'],
                'index_together': {('id', 'first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Category Name', max_length=20, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'index_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Cinema Name', max_length=75, verbose_name='Name')),
                ('address', models.CharField(default='Address', max_length=75, verbose_name='Adress')),
                ('phone', models.CharField(default='Phone', max_length=75, verbose_name='Phone')),
                ('website', models.URLField(default='http://www.kinopark.kz/ru', verbose_name='Link to Cinema Site')),
            ],
            options={
                'verbose_name': 'Cinema',
                'verbose_name_plural': 'Cinemas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CinemaMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_m', to='kinema.Cinema', verbose_name='Cinema')),
            ],
            options={
                'verbose_name': 'Show Time List',
                'verbose_name_plural': 'Show Time Lists',
                'ordering': ['cinema'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Contry Name', max_length=20, verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
                'index_together': {('id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, default='FName', max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(db_index=True, default='LName', max_length=20, verbose_name='Last Name')),
            ],
            options={
                'verbose_name': 'Director',
                'verbose_name_plural': 'Directors',
                'ordering': ['first_name'],
                'index_together': {('id', 'first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Movie Name', max_length=75, verbose_name='Name')),
                ('duration', models.DurationField(default=datetime.timedelta(0), verbose_name='Duration')),
                ('releas_date', models.DateTimeField(verbose_name='Release Date')),
                ('age_restrict', models.PositiveIntegerField(default=0, verbose_name='Age Restriction')),
                ('box_office', models.PositiveIntegerField(default=1000, verbose_name='Box Office')),
                ('plot', models.TextField(default='This is the plot of Movie', verbose_name='The Plot')),
                ('link_trailer', models.URLField(default='https://www.youtube.com/watch?v=hHW1oY26kxQ', verbose_name='Link to Trailer')),
                ('link_poster', models.URLField(default='https://www.quantabiodesign.com/wp-content/uploads/No-Photo-Available.jpg', verbose_name='Link to Poster')),
                ('actors', models.ManyToManyField(to='kinema.Actor', verbose_name='Actors')),
                ('categories', models.ManyToManyField(to='kinema.Category', verbose_name='Categories')),
                ('countries', models.ManyToManyField(to='kinema.Country', verbose_name='Countries')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinema.Director', verbose_name='Director')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(db_index=True, default=2000, verbose_name='Year')),
            ],
            options={
                'verbose_name': 'Year',
                'verbose_name_plural': 'Years',
                'ordering': ['value'],
                'index_together': {('id', 'value')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20, verbose_name='Date Time')),
                ('count', models.PositiveIntegerField(verbose_name='Count of Tickets')),
                ('count_10', models.PositiveIntegerField(verbose_name='Count of $10 Tickets')),
                ('count_20', models.PositiveIntegerField(verbose_name='Count of $20 Tickets')),
                ('count_30', models.PositiveIntegerField(verbose_name='Count of $30 Tickets')),
                ('cost', models.PositiveIntegerField(verbose_name='Price of all Tickets')),
                ('sits', models.CharField(max_length=200, verbose_name='Sits of Ticket')),
                ('mail', models.CharField(max_length=200, verbose_name='Mail')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_t', to='kinema.Cinema', verbose_name='Cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_t', to='kinema.Movie', verbose_name='Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_t', to=settings.AUTH_USER_MODEL, verbose_name='Buyer')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ShowTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Show Time')),
                ('cinema_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_movie', to='kinema.CinemaMovie', verbose_name='Cinema Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Rate')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='kinema.Movie', verbose_name='Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Rated User')),
            ],
            options={
                'verbose_name': 'Rate',
                'verbose_name_plural': 'Rates',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_img', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_img', to='kinema.Movie', verbose_name='Movie')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinema.Year', verbose_name='Year'),
        ),
        migrations.CreateModel(
            name='CommentMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='This is the comment to Movie', verbose_name='Comment')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cm', to='kinema.Movie', verbose_name='Movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_m', to=settings.AUTH_USER_MODEL, verbose_name='Commented User')),
            ],
            options={
                'verbose_name': 'Comment to Movie',
                'verbose_name_plural': 'Comments to Movies',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='CommentCinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='This is the comment to Cinema', verbose_name='Comment')),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_cm', to='kinema.Cinema', verbose_name='Cinema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_c', to=settings.AUTH_USER_MODEL, verbose_name='Commented User')),
            ],
            options={
                'verbose_name': 'Comment to Cinema',
                'verbose_name_plural': 'Comments to Cinemas',
                'ordering': ['user'],
            },
        ),
        migrations.AddField(
            model_name='cinemamovie',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_c', to='kinema.Movie', verbose_name='Movie'),
        ),
        migrations.CreateModel(
            name='CinemaImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinema_img', models.ImageField(blank=True, upload_to='images/', verbose_name='Image')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_img', to='kinema.Cinema', verbose_name='Cinema')),
            ],
        ),
        migrations.AlterIndexTogether(
            name='movie',
            index_together={('id', 'name')},
        ),
    ]
