# Generated by Django 2.2.7 on 2019-12-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='time',
            field=models.CharField(default='0', max_length=20, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.CharField(default='0', max_length=20, verbose_name='Date'),
        ),
    ]
